ckpt_path: null

controller:
  hidden_dims: [128, 64]
  ckpt_path: null

reward:
  hidden_dims: [128, 64]
  ckpt_path: null

mdn: 
  hidden_size: 256
  num_layers: 1
  num_mixtures: 5
  ckpt_path: null
  
vae:
  name: cnn_vae
  type: cnn
  latent_dim: 64
  input_shape: [3, 64, 64]
  ckpt_path: null