defaults:
  - default
  - model/vae: ???
  - data: ???
  
learning_rate: 1e-4
batch_size: 64
num_epochs: 100
num_workers: 4

mask_enabled: False
mask_ratio: 0.5
patch_size: 8
log_dir: ./logs
save_ckpt_dir: ???
